#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local pth_config="$(echo "$PWD" | perl -pe 's{.*?/org/}{}; s{/+}{-}g')"
  local adj_config="./$(echo "$pth_config" | perl -pe 's{[^-]+$}{}; s{[^-]+}{..}g; s{-}{/}g')"

	terraform remote config -backend=s3 -backend-config="bucket=$(hcltool $adj_config/terraform.tfvars | jq -r '.s3_remote_state')" -backend-config="region=$(hcltool $adj_config/terraform.tfvars | jq -r '.aws_region')" -backend-config="key=$pth_config/terraform.tfstate"
}

source sub "$BASH_SOURCE" "$@"
