#!/usr/bin/env bash

function switch_credentials {
  local a
  for a in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_SESSION_EXPIRATION; do
    local b="${CONTEXT_ORG}_$a"
    export "$a"="${!b}"
  done
}

function __imma {
	case "${1:-}" in
    assume)
      shift # 'assume'

      eval $(command imma role "$@")
      switch_credentials
      ;;

    switch)
      shift # 'switch'

      switch_credentials

      if [[ -z "${AWS_SESSION_EXPIRATION:-}" ]]; then
        "${FUNCNAME[1]}" assume "$@"
      fi

      if [[ -n "${AWS_SESSION_EXPIRATION:-}" ]]; then
        local time_left="$(( $(gdate -d "$AWS_SESSION_EXPIRATION" +%s) - $(date +%s) ))"
        if [[ "$time_left" -lt 600 ]]; then
          "${FUNCNAME[1]}" assume "$@"
        fi
      fi
      ;;

    *)
      command "${FUNCNAME[1]}" "$@"
      ;;
  esac
}

function _imma {
  local shome="${_imma_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  source imma_common

  __imma "$@"
}
