#!/usr/bin/env bash

function _imma {
	case "${1:-}" in
    assume)
      shift # 'assume'
      local nm_role="${1:-administrator}"; shift || true
      eval $(command imma role "$nm_role")
      ;;
    *)
      command "${FUNCNAME[1]}" "$@"
      ;;
  esac
}
