#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_region="$(cat .terraform/terraform.tfstate 2>/dev/null | jq -r '.modules[0].outputs.aws_region.value//""')"
  if [[ -z "$nm_region" ]]; then
    nm_region="$(hcltool terraform.tfvars 2>/dev/null | jq -r '.aws_region')"
  fi

  export AQ_STATE="${PWD}/.aq"
  mkdir -p "$AQ_STATE"

  export AQ_ACCOUNT_ID="$(cat .terraform/terraform.tfstate 2>/dev/null | jq -r '.modules[1].resources["data.terraform_remote_state.global"].primary.attributes.aws_account_id')"

  ${nm_region:+exec aws "${nm_region}"} exec aws "$@"
}

source sub-chain "$BASH_SOURCE" "$@"
