#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local tmp_credentials="$1"; shift

  rm -f "$tmp_credentials"
  unset AWS_SHARED_CREDENTIALS_FILE

  exec "$@"
}

source sub "$BASH_SOURCE" "$@"
