#!/usr/bin/env bash

function paste_buffer {
  cat | if type -P pbcopy >/dev/null; then
    local a
    read -n 6 a
    cat <<< "$a"
    echo -n "$a" | pbcopy
  else
    cat
  fi
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ "$#" -gt 0 ]]; then
    export CONTEXT_ORG="$1"; shift
  fi

  gpg -q --batch --yes --decrypt --output - "$HOME/.aws/totp-${CONTEXT_ORG}.gpg" | perl -pe 's{\s*$}{}' | (set +u; source "$shome/vendor/virtualenv/bin/activate"; imma totp code) \
    | paste_buffer
}

source sub "$BASH_SOURCE" "$@"
