#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_env="$1"; shift

  local tmp_fogg="$(mktemp -t XXXXXX)"
  hcltool "$shome/common/env.tf" > "$tmp_fogg"

  cat "$tmp_fogg" \
    | jq -r '.module | map(.source) | unique[]' \
    | (runmany 'cat $1/export.json'; runmany 'hcltool ../../common/$1.tf' global) \
    | jq -s 'reduce .[] as $exp ({}; . * $exp)' > "$tmp_fogg.modules"

	jq -n --argfile seed     "$tmp_fogg" \
		    --argfile modules  "$tmp_fogg.modules" \
        --arg     az_count "$(aws ec2 describe-availability-zones --region $(cat ../../env/global/.terraform/terraform.tfstate | jq -r --arg env_name "$nm_env" '.modules[0].outputs.env_region.value[$env_name]') | jq -r '.AvailabilityZones | length')" \
	      --arg     env_name "$nm_env" '$seed * $modules |
	      	.variable.global_remote_state |= { default: "../../env/global/.terraform/terraform.tfstate" } |
					.variable.env_name            |= { default: "\($env_name)" } |
          .variable.az_count            |= { default: "\($az_count)" }'
}

source sub "$BASH_SOURCE" "$@"
