#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  imma credentials env > "$HOME/.bashrc.secrets.1"
  mv -f "$HOME/.bashrc.secrets.1" "$HOME/.bashrc.secrets"
}

source sub "$BASH_SOURCE" "$@"
