#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  cat <<EOF
[default]
aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
aws_access_key_id = ${AWS_ACCESS_KEY_ID}
aws_session_token= ${AWS_SESSION_TOKEN}
EOF
}

source sub "$BASH_SOURCE" "$@"
