#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  _imma assume "$@"
  imma credentials cache >/dev/null
}

source sub "$BASH_SOURCE" "$@"
