#!/usr/bin/env bash

source normalize

export CONTEXT_ENV="${0##*-}"

function main {
  local shome="${_imma_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  exec "$@"
}

source sub-middleware "$BASH_SOURCE" "$@"
