#!/usr/bin/env bash

function paste_buffer {
  cat | if type -P pbcopy >/dev/null; then
    local a
    read -n 6 a
    cat <<< "$a"
    echo -n "$a" | pbcopy
  else
    cat
  fi
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_key="$1"; shift

  (vault read --format json totp/code/"${nm_key}" || { imma totp load "$nm_key" && vault read --format json totp/code/"${nm_key}"; })| jq -r '.data.code' | paste_buffer
}

source sub "$BASH_SOURCE" "$@"
