#!/usr/bin/env bash

function switch_credentials {
  local a
  for a in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_SESSION_EXPIRATION; do
    local b="${CONTEXT_ORG}_$a"
    export "$a"="${!b}"
  done
  
  if type -P "env-${CONTEXT_ORG}" >/dev/null; then
    source "env-${CONTEXT_ORG}"
  fi
}

function __imma {
	case "${1:-}" in
    assume)
      shift # 'assume'
      case "$#" in
        0)
          echo "ERROR: syntax: context_org role region" 1>&2
          return 1
          ;;
        *)
          eval $(command imma role "$@")
          switch_credentials
          ;;
      esac
      ;;
    *)
      command imma "$@"
      ;;
  esac
}

function _imma {
  local shome="${_imma_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  source imma_common

  __imma "$@"
}
