#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_role="$1"; shift
  local nm_prefix="${CONTEXT_ORG}_${nm_role#${CONTEXT_ORG}-}"

  local tmp_credentials="$(mktemp -t XXXXXX)"
  trap "$(printf 'rm -vf "%q" 1>&2' "$tmp_credentials")" EXIT

  if [[ -f "$HOME/.aws/credentials-${CONTEXT_ORG}.gpg" ]]; then
    gpg -q --batch --yes --output "$tmp_credentials" --decrypt "$HOME/.aws/credentials-${CONTEXT_ORG}.gpg"
    export AWS_SHARED_CREDENTIALS_FILE="$tmp_credentials"
  fi

  local arn_role="$(cat "$HOME/.aws/assume" | jq -r --arg role "$nm_prefix" '.[$role].role')"
  local id_mfa="$(cat "$HOME/.aws/assume" | jq -r --arg role "$nm_prefix" '.[$role].mfa')"

  local tmp_sts="$(mktemp -t XXXXXX)"
  trap "$(printf 'rm -vf "%q" "%q" 1>&2' "$tmp_credentials" "$tmp_sts")" EXIT
  
  unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_SESSION_EXPIRATION AWS_DEFAULT_REGION

  local the_code=
  local last_code=

  if [[ -n "${1:-}" ]]; then
    the_code="$1"; shift
    aws sts assume-role --role-arn "$arn_role" --role-session-name "${CONTEXT_ORG}-$LOGNAME" --serial-number "$id_mfa" --token-code "$the_code" > "$tmp_sts"
  else
    while true; do
      while [[ "$the_code" == "$last_code" ]]; do
        the_code="$(imma totp)"
        sleep 1
      done
      last_code="$the_code"
      if aws sts assume-role --role-arn "$arn_role" --role-session-name "${CONTEXT_ORG}-$LOGNAME" --serial-number "$id_mfa" --token-code "$the_code" > "$tmp_sts"; then
        break
      fi
    done
  fi

  unset AWS_SHARED_CREDENTIALS_FILE
  rm -f "$tmp_credentials"

  export "${CONTEXT_ORG}_AWS_ACCESS_KEY_ID"="$(cat "$tmp_sts" | jq -r '.Credentials.AccessKeyId')"
  export "${CONTEXT_ORG}_AWS_SECRET_ACCESS_KEY"="$(cat "$tmp_sts" | jq -r '.Credentials.SecretAccessKey')"
  export "${CONTEXT_ORG}_AWS_SESSION_TOKEN"="$(cat "$tmp_sts" | jq -r '.Credentials.SessionToken')"
  export "${CONTEXT_ORG}_AWS_SESSION_EXPIRATION"="$(cat "$tmp_sts" | jq -r '.Credentials.Expiration')"
  rm -f "$tmp_sts"

  unset AWS_PROFILE

  if [[ "$#" == 0 ]]; then
    set | egrep '^'"${CONTEXT_ORG}_" | sed 's#^#export #'
  else
    exec "$@"
  fi
}

source sub "$BASH_SOURCE" "$@"
