#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  "$shome/vendor/virtualenv/bin/python" -c "import onetimepass" 2>/dev/null
}

main "$@"
